INSERT INTO Greenways (
	MID,
	Name,
	Map_URL,
	LengthInMiles,
	Length,
	EndPoints,
	Surface,
	Terrain,
	Navigation,
	Parking,
	Amenities,
	Nearby_Amenities,
	Connections,
	Accessibility)
VALUES
( 1,
	N'Bethabara',
	N'http://maps.google.com/maps/ms?msa=0&msid=211434024492203917841.0004b37703c0edefe45e7&ie=UTF8&t=m&source=embed&ll=36.153885,-80.301561&spn=0.010395,0.012875&z=15',
	2.7,
	N'Part of a 9-mile network of woodland trails and wetland boardwalks through Historic Bethabara Park (HBP).',
	N'Crowne Oaks Apartments to Reynolda Commons Shopping Center.',
	N'Paved between Old Town Road and Old Town Drive, and from Midkiff Road to Reynolda Road; otherwise, a variety of unpaved surfaces.',
	N'Paved sections are flat.',
	N'Bethabara Greenway is bisected by Old Town Drive. Pedestrians and cyclists should use extreme caution when crossing. There are blind curves in both directions, and currently no crosswalk or sidewalk. The City of Winston-Salem does have plans to upgrade this dangerous intersection.',
	N'Paved and gravel lots at HBP Visitor Center; unmarked gravel lots on Old Town Drive; unmarked on-street parking at the end of Midkiff Road and at the end of Indiana Avenue  Ext.; unmarked paved parking at Reynolda Commons Shopping Center (from there greenway access is down a set of wooden steps on Reynolda Road).',
	N'Benches, trash cans, bulletin boards, Nature and historical interpretive signage.',
	N'At HBP Visitor Center (open 10:30-4:30 Tue.-Fri., 1:30-4:30 Sat. and Sun.): restrooms, water fountain, maps of trails. At Bethabara City Park (parking off Old Town Drive): portable toilet, playground, parcourse and picnic area with grill.',
	N'One paved section of the Bethabara Greenway runs behind HBP''s restored 18th century church and potter''s house, archaeological ruins, reconstructed palisade fort and gardens. Reynolds Commons Shopping Center, at the Reynolda Road end of the greenway, offers a grocery, pharmacy, restaurants and other businesses.',
	N'The stretch of paved greenway along Mill Creek is not easy to find. An accessible entrance is at the end of Midkiff Rd. (off Reynolda Road, past Old Town Drive), where you can park on the street. There is a bit of hill and some rough ground around the barricade, but after that it''s smooth going.'),
( 2,
	N'Bowen Branch',
	N'http://maps.google.com/maps/ms?msa=0&msid=211434024492203917841.0004b348a1e586247b96e&ie=UTF8&t=m&source=embed&ll=36.115898,-80.211439&spn=0.0052,0.006437&z=16',
	.3,
	null,
	N'New Walkertown Road (US 311) to Bowen Boulevard.  ',
	N'Asphalt.',
	N'Low hills.',
	null,
	N'Paved lots at Twin City ball field complex, across New Walkertown from the greenway entrance. No parking on Bowen Boulevard.',
	N'Benches.',
	N'Portable toilets at Twin City ballfield complex.',
	N'Newell-Massey Greenway, Winston Lake Park, Winston-Lake YMCA. Ashley Middle School and Bowen Boulevard Park and Fitness Course are west on Bowen Boulevard.',
	N'No wheelchair access on Bowen Boulevard end. To enter from New Walkertown, wheelchair users must pass under a cable suspending a stop sign.'),
( 3,
	N'Gateway Commons',
	N'http://maps.google.com/maps/ms?t=m&msa=0&msid=211434024492203917841.0004b3769617c51dcc36e&ie=UTF8&source=embed&ll=36.113957,-80.247831&spn=0.010401,0.012875&z=15',
	.8,
	N'Loops through the park,',
	N'Northwest Boulevard to Glenn Avenue,',
	N'Asphalt.',
	N'Long, moderately steep hill,',
	null,
	N'Large paved lot at Northwest Boulevard entrance.',
	N'Benches, two playgrounds, picnic tables with grills, picnic shelter, trash cans.' ,
	N'Kimberly Park offers a swimming pool, playground, fitness course and picnic shelter. Groceries, gas and fast food are on Northwest Boulevard,',
	N'Martin Luther King Jr. Community Center; Kimberly Park Elementary School.',
	N'A short but flat section leads from the parking lot to an attractive bridge over Peters Creek.'),
( 4,
	N'Muddy Creek',
	N'http://maps.google.com/maps/ms?msa=0&msid=211434024492203917841.0004b2f5941e17b5b0f60&ie=UTF8&t=m&source=embed&ll=36.10945,-80.354862&spn=0.020803,0.025749&z=14',
	2.91,
	N'Plus two half-mile spurs at northern end.',
	N'Country Club Road to Summerfield neighborhood,',
	N'Asphalt.',
	N'Flat, except at Robinhood Road underpass.',
	null,
	N'Larger gravel lot off Meadowlark Drive, just south of Meadowlark schools. Gravel roadside parking lot on Robinhood Road just west of Muddy Creek bridge. Also, parking across Robinhood Road at the entrance to Jefferson School.',
	N'Portable toilet in Meadowlark parking area, posted maps, dog waste stations, trash cans,',
	null,
	N'Meadowlark Elementary and Middle schools, Jefferson Elementary School,',
	N'Meadowlark Drive parking lot has two paved handicapped parking spaces.'),
( 5,
	N'Newell-Massey',
	N'http://maps.google.com/maps/ms?msa=0&msid=211434024492203917841.0004b320750b2638faf99&ie=UTF8&t=m&source=embed&ll=36.107265,-80.212297&spn=0.010402,0.012875&z=15',
	1.2,
	null,
	N'Waterworks Road to Old Greensboro Road.  ',
	N'Asphalt.',
	N'Flat.',
	null,
	N'Paved lot on Waterwords Road, between the greenway entrance and the Twin City ballfield complex. No parking on Old Greensboro end.',
	N'Benches',
	N'Portable toilets at Twin City ballfield complex.',
	N'Winston Lake Park; Winston Lake YMCA; Bowen Branch Greenway; Brushy Fork Greenway (under construction). Runs by the back fence of Evergreen Cemetery,',
	N'Flat and easily accessed, this is a good greenway for wheelchairs. However, it is not presently accessible from Old Greensboro Road,'),
( 6,
	N'Peachtree',
	N'http://maps.google.com/maps/ms?t=m&msa=0&msid=211434024492203917841.0004b335cb96f1b6ada04&ie=UTF8&source=embed&ll=36.083511,-80.208607&spn=0.010405,0.012875&z=15',
	.6,
	null,
	N'Salem Creek Greenway to a dead end behind Reynolds Park Golf Course,',
	N'Asphalt.',
	N'Moderate hills,',
	N'The greenway is interrupted by a section of sidewalk and a street crossing at Peachtree Street,',
	N'Curbside parking along Peachtree Street.',
	N'Benches.',
	null,
	N'Salem Creek Trail, Reynolds Park Golf Course. An extension to Waughtown Street is planned,',
	N'The latter part of this trail involves a long climb up a low hill.'),
( 7,
	N'Salem Lake',
	N'http://maps.google.com/maps/ms?msa=0&msid=211434024492203917841.0004b34971ae1ad6d743a&ie=UTF8&t=m&source=embed&ll=36.099117,-80.179853&spn=0.020805,0.025749&z=14',
	7,
	N'Loop.',
	null,
	N'Unpaved, uneven.',
	N'Long hills.',
	N'Sunrise to sunset.',
	N'Paved and unpaved lots by the fishing station and picnic area. A gravel lot up the hill on Salem Lake Road is used when the gates to the lake are locked. Also: paved parking at the Linville Road end of the lake; a small unpaved lot at the end of New Greensboro Road, used primarily by horseback riders.',
	N'Posted maps, distance markings, benches, bulletin boards. Restrooms and refreshments in the fishing station. Water at Linville Road parking lot. Horses are permitted. Also at the dam end: fishing, boat rentals, picnic tables with grills, playground.',
	null,
	N'Salem Creek Greenway, Salem Lake Road, Linville Road.',
	N'The north side of the trail, though still unpaved, is less hilly than the south side.'),
( 8,
	N'Salem Creek',
	N'http://maps.google.com/maps/ms?msa=0&msid=211434024492203917841.0004b32209ba891d1c153&ie=UTF8&t=m&source=embed&ll=36.083511,-80.223885&spn=0.041619,0.051498&z=13',
	5.8,
	null,
	N'Marketplace Mall to Salem Lake,',
	N'Asphalt.',
	N'Several long hills.',
	N'The posted maps are essential: It takes some tricky turns to zig-zag over two pedestrian bridges and under Broad and Main streets, but it is possible to ride the entire trail without entering traffic.',
	N'Paved lots at Marketplace Mall (go all the way to the back); Washington Park (off Broad Street at the power station); behind the retail shopping area on Salem Avenue; at the tennis courts near the traffic circle at Main Street and Salem Avenue; and at Reynolds Park on Reynolds Park Drive (just west of the golf course). Paved and gravel lots at Salem Lake.',
	N'Posted maps, distance markings, benches, bulletin boards. At Washington Park: portable toilet in parking area, workout stations, and dog park with dog waste station.',
	N'Restrooms and water at Salem Lake.',
	N'Marketplace Mall, with shopping and food; Washington Park''s picnic shelters, playgrounds, ball fields and basketball courts; the Strollway to downtown; Old Salem, the restored Moravian village with numerous museums; tennis courts at Central Park; Salem College; UNC-School of the Arts; Winston-Salem State University, with Diggs Gallery; Reynolds Park Golf Course; Reynolds Park recreation center and pool; Salem Lake, with boating, fishing, picnic areas and playground.',
	N'At Civitan Park there is a refreshingly flat stretch on this otherwise hilly greenway. With a handicapped placard you can park for free behind WSSU''s Anderson Center (at the end of the parking lot that begins where Reynolds Park Drive dead-ends into Martin Luther King Drive). Take the sloping bridge over Salem Creek to the trail.'),
( 9,
	N'Silas Creek',
	N'http://maps.google.com/maps/ms?msa=0&msid=211434024492203917841.0004b2f62b5e90176b81b&ie=UTF8&t=m&source=embed&ll=36.108271,-80.304608&spn=0.010401,0.012875&z=15',
	.81,
	N'Includes a side trail on the west side of the creek.  ',
	N'Yorkshire Road to Robinhood Road. At the Robinhood Road end, a long set of wooden steps leads to the street above.',
	N'Asphalt.',
	N'Flat, after hill at parking lot,',
	null,
	N'A paved lot at Shaffner Park, off Yorkshire Road. Also on-street parking at Burkeshore Road.',
	N'Portable toilet in parking lot, water fountains, benches, posted map, distance markings, bulletin board.',
	N'Shaffner Park has tennis courts, soccer fields and playground. Sherwood Parcourse, across Silas Creek Parkway, also has portable toilets, benches.',
	N'Sherwood Forest neighborhood, Sherwood Elementary School. An underground walkway gets pedestrians across Silas Creek Parkway.',
	N'The short but steep hill and street-crossing from the parking lot on Yorkshire Road can be avoided. Drive to the end of Burkeshore Road (off Shoreland Road between Yorkshire and Robinhood) and park on the street.'),
(10,
	N'Strollway',
	N'http://maps.google.com/maps/ms?msa=0&msid=211434024492203917841.0004b3363d36536ff8627&ie=UTF8&t=m&source=embed&ll=36.089407,-80.245085&spn=0.020808,0.025749&z=14',
	1.2,
	null,
	N'Downtown and Salem Creek. Begins at Trade and Eighth streets, becoming barrier-free at Second, between Cherry and Liberty. Ends at the traffic circle at Main Street and Salem Avenue.   ',
	N'Paved and gravel in asphalt, with some loose gravel over asphalt.',
	null,
	N'Pedestrians and cyclist must yield to cross traffic! Numerous street crossings are not marked. Be especially careful at Second Street, First Street, in the parking lots below the Business 40 overpass, Brookstown Avenue, Academy Street, Walnut Street and Salem Avenue.',
	N'On-street or deck parking downtown; Old Salem Visitor Center (west of Main on Walnut Street); Salem Avenue (behind businesses west of Main).',
	N'Posted maps, benches, water fountain (south side of First Street),',
	N'Restrooms, water and food in Old Salem Visitor Center (open 9-5 Tue.-Sat.; 12:30-5 Sun. ).',
	N'Food, shopping, entertainment downtown; Children''s Museum; Old Salem; Salem Creek Greenway,',
	N'When traveled from north to south, the section below Second Street is a pleasant downhill ride. Assistance may be needed for the steep decline just below First Street.');

	
INSERT INTO Events (
	MID,
	StartDate,
	StartTime,
	EndDate,
	EndTime,
	EventInterval,
	Location,
	Description)
VALUES
( 1,
	'2012-11-09',
	'19:00:00',
	null,
	null,
	null,
	'TBA',
	N'WS Greenways presents a talk by Russ DuBois, executive director of the Creative Corridors Coalition, who will discuss his organization''s efforts to make downtown Winston-Salem''s roadway infrastructure more attractive and more pedestrian friendly. Please join us!'),
( 2,
	'2012-11-03',
	'3:00:00',
	null,
	null,
	null,
	'Salem Lake fishing station',
	N'At the Salem Lake Dam Walk and Talk you can learn about the newly completed dam from engineer Courtney Driver. The walk to the dam will begin at the fishing station. After the talk, everyone is encouraged to either walk or bike the Salem Creek Greenway or Salem Lake Trail, so bring your bike or your walking shoes! Rescheduled from October. For more info, call 336-703-3110'),
( 3,
	'2012-11-04',
	'3:00:00',
	null,
	'5:30:00',
	null,
	'Wake Forest University - ZSR Library',
	N'This week''s Community Bike Ride will be backwards, sort of. Instead of starting and ending at Caffe Prada, as usual, riders will start and end at Wake Forest University, with a gelato stop at Caffe Prada along the way. Riders will join Wake students, faculty and staff to help raise awareness of biking among the WFU community and to draw attention to the need for improved bicycle and pedestrian corridors between WFU and downtown Winston-Salem. The first 25 to sign up will get an official WS Greenways water bottle, and everyone gets a free gelato. The slow-paced, ten-mile ride is open to all. Sign up <a href="http://pdc.wfu.edu/event/5584/">here</a>. Co-sponsored by the WFU Institute for Public Engagement.'),
( 4,
	'2012-10-03',
	'10:00:00',
	null,
	'12:00:00',
	null,
	'W.R. Anderson Jr. Recreation Center, 2450 Reynolds Park Road',
	N'Check out the city''s proposed master plan for the quarry site park, which includes the Waughtown Connector Greenway The 200-acre site will be developed for public recreation use while incorporating measures to conserve the unique ecosystem that has developed in and around the water bodies in the old quarry.'),
( 5,
	'2012-10-14',
	null,
	'2012-10-28',
	null,
	7,
	'Caffe Prada, corner of Broad and Fourth streets.',
	N'Winston-Salem Community Bike Ride often includes the city''s greenways on its ten-mile route, which changes each Sunday. Everyone is welcome. Start times are in flux this month. For more info look <a href="http://www.bikews.com/">here</a>.'),
( 6,
	'2012-10-16',
	'17:30:00',
	null,
	null,
	null,
	'Wake Forest BioTech Place, 575 North Patterson Ave.',
	N'At its Annual Community Celebration, our friends at the Creative Corridors Coalition and the City of Winston-Salem will unveil the design concepts for the Salem Creek Connector, a roadway that will cross the Salem Creek Greenway as it connects U.S. 52 with downtown. Creative Corridors is working with NCDOT to make the project more aesthetically attractive and reflect the city''s devotion to arts, culture and innovation.'),
( 7,
	'2012-10-21',
	'15:00:00',
	null,
	null,
	null,
	'Corpening Plaza, 231 West First St.',
	N'2nd Annual Tour de Winston 5K Walk & Tour will take participants over or under 10 of the bridges that are being re-imagined by the Creative Corridors Coalition in preparation for the massive redevelopment of Business 40 through downtown. You can walk at your own pace or in group led by CCC guides, and you can voice your ideas for making downtown''s corridors more attractive and pedestrian-friendly. Adult entry fee of $15 includes t-shirt, sandwiches from Camino Bakery, snacks from Chad''s Carolina Corn, and admission to the post-walk party featuring music, games and giveaways. Children 12 and under participate for free, and all children who complete the walk will receive a free scoop of frozen custard from Wolfies. Registration at 2 p.m., walk begins at 3, and post-walk party is 4 to 6 @ Corpening Plaza, 231 West First St.'),
( 8,
	'2012-10-27',
	'10:00:00',
	null,
	'13:00:00',
	null,
	'The new entrance to Bethabara Greenway, next to Bethabara Moravian Church, 2100 Bethabara Road',
	N'If planting trees on the Newell/Massey Greenway this Saturday doesn''t sound like your cup of tea, then we''ve got an excellent alternative for you: You can plant a bush at Bethabara Greenway instead! Our friends at Forsyth Audubon are installing a bird-friendly landscape of berry-bearing native trees and shrubs at the new entrance to Bethabara Greenway.  If you''d like to help, bring work gloves and tools such as shovels, pitchforks, large watering cans and wheelbarrows, if you have them.'),
( 9,
	'2012-10-27',
	null,
	null,
	null,
	null,
	'Forsyth County or 50-mile radius around Winston-Salem',
	N'The second-annual autodrop slingshot lets teams of bicyclists set their own route to reach as many predetermined checkpoints as possible. Checkpoints are within a 50-mile radius of Winston-Salem, or you can choose the ''local yokel'' race to stay within Forsyth County. Either way, riders must return within a strict 7-hour limit. We hear that some of the checkpoints involve Winston-Salem''s greenways! Details <a href="http://2012slingshot.blogspot.com/p/the-low-down.html">here</a>.'),
(10,
	'2012-10-27',
	'09:00:00',
	null,
	'12:00:00',
	null,
	'2790 New Walkertown Road',
	N'This year''s Community Roots Day includes tree-planting on the Newell-Massey Greenway. Sponsored by the Community Appearance Commission, Keep Winston-Salem Beautiful, and the City of Winston-Salem Vegetation Management Department, this volunteer tree-planting event has been adding shade, fresh air and extra character to our neighborhoods for twenty years now. Registration at the ball fields. If you are interested in participating go to this <a href="http://www.cityofws.org/Home/Departments/KeepWinston-SalemBeautiful/Forms/KWSBVolunteerSign-Up">link</a>, call 727-8013 or write georges@cityofws.org.'),
(11,
	'2012-10-06',
	null,
	null,
	null,
	null,
	'GPS coordinate 36.094427,-80.218855',
	N'WS Greenways will be cleaning up Bushy Fork Greenway as part of the Big Sweep, a community-wide cleanup of local waterways sponsored by Keep Winston-Salem Beautiful. All supplies and lunch are provided. If you want to help, just email us at wsgreenways@gmail.com so we''ll know how many lunches to order! Oh yeah, and dress for wading, if you''re up to it. Directions: From downtown WS, take Business 40 to the Lowery Street exit. At the end of the ramp, turn right onto Lowery Street. The greenway entrance is 0.8 mile on the right.'),
(12,
	'2012-10-07',
	'15:00:00',
	null,
	null,
	null,
	'Salem Lake parking lot off Salem Lake Road',
	N'At the Salem Lake Dam Walk and Talk you can learn about the newly completed dam from engineer Toneq McCullough. The walk to the dam will begin in the parking lot off Salem Lake Road. After the talk, everyone is encouraged to either walk or bike the Salem Creek Greenway or Salem Lake Trail, so bring your bike! For more info, call 336-703-3110');